services:
  pg-a:
    build: ./postgres
    container_name: pg-a
    environment:
      - POSTGRES_PASSWORD=postgres
      - REPLICATION_USER=replicator
      - REPLICATION_PASSWORD=replpass
      - NODE_NAME=pg-a
      - ROLE=primary
      - DOCKER_HOST=tcp://host.docker.internal:2375
    volumes:
      - pg-a-data:/var/lib/postgresql/data
      - ./pgconf/pg_a:/docker-entrypoint-initdb.d:ro
    networks:
      - pgnet
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      retries: 5

  pg-b:
    build: ./postgres
    container_name: pg-b
    environment:
      - POSTGRES_PASSWORD=postgres
      - REPLICATION_USER=replicator
      - REPLICATION_PASSWORD=replpass
      - PRIMARY_HOST=pg-a
      - PRIMARY_PORT=5432
      - NODE_NAME=pg-b
      - ROLE=replica
      - REPL_MODE=synchronous
      - APPLICATION_NAME=pg_b
      - DOCKER_HOST=tcp://host.docker.internal:2375
    depends_on:
      - pg-a
    volumes:
      - pg-b-data:/var/lib/postgresql/data
      - ./pgconf/pg_b:/docker-entrypoint-initdb.d:ro
    networks:
      - pgnet
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      retries: 5

  pg-c:
    build: ./postgres
    container_name: pg-c
    environment:
      - POSTGRES_PASSWORD=postgres
      - REPLICATION_USER=replicator
      - REPLICATION_PASSWORD=replpass
      - PRIMARY_HOST=pg-a
      - PRIMARY_PORT=5432
      - NODE_NAME=pg-c
      - ROLE=replica
      - REPL_MODE=asynchronous
      - APPLICATION_NAME=pg_c
      - DOCKER_HOST=tcp://host.docker.internal:2375
    depends_on:
      - pg-a
    volumes:
      - pg-c-data:/var/lib/postgresql/data
      - ./pgconf/pg_c:/docker-entrypoint-initdb.d:ro
    networks:
      - pgnet
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      retries: 5

  pgpool:
    build: ./pgpool
    container_name: pgpool
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
      - PGPOOL_PCP_USER=pgpool
      - PGPOOL_PCP_PASSWORD=pgpoolpass
    volumes:
      - ./pgpool/conf/pgpool.conf:/config/pgpool.conf
      - ./pgpool/conf/pool_hba.conf:/config/pool_hba.conf
      - ./pgpool/conf/pool_passwd:/etc/pgpool2/pool_passwd
      # - ./pgpool/conf/pcp.conf:/etc/pgpool2/pcp.conf
      - ./pgpool/failover.sh:/scripts/failover.sh
    ports:
      - 9999:9999
    networks:
      - pgnet
    depends_on:
      pg-a:
        condition: service_healthy
      pg-b:
        condition: service_healthy
      pg-c:
        condition: service_healthy

  client:
    image: postgres:15
    container_name: pg-client
    depends_on:
      - pgpool
    volumes:
      - ./pgconf/pg_client:/scripts
    networks:
      - pgnet
    tty: true
    stdin_open: true
    command: ["sleep","infinity"]

volumes:
  pg-a-data:
  pg-b-data:
  pg-c-data:

networks:
  pgnet:
    driver: bridge
