services:
  pg-a:
    build: ./postgres
    container_name: pg-a
    environment:
      - POSTGRES_PASSWORD=postgres
      - REPLICATION_USER=replicator
      - REPLICATION_PASSWORD=replpass
      - NODE_NAME=pg-a
      - ROLE=primary
    volumes:
      - pg-a-data:/var/lib/postgresql/data
      - ./pgconf/pg_a:/docker-entrypoint-initdb.d:ro
    networks:
      - pgnet
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      retries: 5

  pg-b:
    build: ./postgres
    container_name: pg-b
    environment:
      - POSTGRES_PASSWORD=postgres
      - REPLICATION_USER=replicator
      - REPLICATION_PASSWORD=replpass
      - PRIMARY_HOST=pg-a
      - PRIMARY_PORT=5432
      - NODE_NAME=pg-b
      - ROLE=replica
      - REPL_MODE=synchronous
      - APPLICATION_NAME=pg_b
    depends_on:
      - pg-a
    volumes:
      - pg-b-data:/var/lib/postgresql/data
      - ./pgconf/pg_b:/docker-entrypoint-initdb.d:ro
    networks:
      - pgnet
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      retries: 5

  pg-c:
    build: ./postgres
    container_name: pg-c
    environment:
      - POSTGRES_PASSWORD=postgres
      - REPLICATION_USER=replicator
      - REPLICATION_PASSWORD=replpass
      - PRIMARY_HOST=pg-a
      - PRIMARY_PORT=5432
      - NODE_NAME=pg-c
      - ROLE=replica
      - REPL_MODE=asynchronous
      - APPLICATION_NAME=pg_c
    depends_on:
      - pg-a
    volumes:
      - pg-c-data:/var/lib/postgresql/data
      - ./pgconf/pg_c:/docker-entrypoint-initdb.d:ro
    networks:
      - pgnet
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      retries: 5

  pgpool:
    image: bitnami/pgpool:latest
    container_name: pgpool
    environment:
      - PGPOOL_BACKENDS=pg-a:5432:postgres,pg-b:5432:postgres,pg-c:5432:postgres
      - PGPOOL_SR_CHECK_PERIOD=5
      - PGPOOL_ENABLE_POOL_HBA=yes
      - PGPOOL_PORT=9999
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpass
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
      - PGPOOL_HEALTH_CHECK_USER=postgres
      - PGPOOL_HEALTH_CHECK_PASSWORD=postgres
      - PGPOOL_BACKEND_NODES=0:pg-a:5432,1:pg-b:5432,2:pg-c:5432
    volumes:
      - ./pgpool/conf/pgpool.conf:/opt/bitnami/pgpool/conf/pgpool.conf
      - ./pgpool/conf/pool_hba.conf:/opt/bitnami/pgpool/conf/pool_hba.conf
      - ./pgpool/conf/pool_passwd:/opt/bitnami/pgpool/conf/pool_passwd
    ports:
      - 9999:9999
    networks:
      - pgnet
    depends_on:
      - pg-a
      - pg-b
      - pg-c

  client:
    image: postgres:15
    container_name: pg-client
    depends_on:
      - pgpool
    networks:
      - pgnet
    tty: true
    stdin_open: true
    command: ["sleep","infinity"]

volumes:
  pg-a-data:
  pg-b-data:
  pg-c-data:

networks:
  pgnet:
    driver: bridge
